/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javastdapp;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JComboBox;
import java.awt.event.*;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.*;
import javax.swing.*;

/**
 *
 * @author shreeya
 */
public class addInstructor extends javax.swing.JFrame {

    /**
     * Creates new form addInstructor
     */
    instructors crs = new instructors();

    public addInstructor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_Iname = new javax.swing.JTextField();
        jTextField_mname = new javax.swing.JTextField();
        jButton_addI = new javax.swing.JButton();
        jButton_ADDc = new javax.swing.JButton();
        jComboBox_cname = new javax.swing.JComboBox<>();
        jlabel_email = new javax.swing.JLabel();
        jTextField_email = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel1.setText("Add Instructor");

        jLabel2.setText("Instructor Name:");

        jLabel3.setText("Course Name:");

        jLabel4.setText("Module Name:");

        jlabel_email.setText("Email");

        jButton_addI.setBackground(new java.awt.Color(0, 51, 51));
        jButton_addI.setForeground(new java.awt.Color(242, 242, 242));
        jButton_addI.setText("Add Instructor");
        jButton_addI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addIActionPerformed(evt);
            }
        });

        jButton_ADDc.setBackground(new java.awt.Color(0, 51, 51));
        jButton_ADDc.setForeground(new java.awt.Color(242, 242, 242));
        jButton_ADDc.setText("Cancel");
        jButton_ADDc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ADDcActionPerformed(evt);
            }
        });

        jComboBox_cname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BIT", "BBA", "BIBM", " " }));

        jlabel_email.setText("Email:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jlabel_email))
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_Iname)
                                    .addComponent(jTextField_mname)
                                    .addComponent(jComboBox_cname, 0, 137, Short.MAX_VALUE)
                                    .addComponent(jTextField_email)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_addI)
                                .addGap(75, 75, 75)
                                .addComponent(jButton_ADDc)))))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_Iname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox_cname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_mname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel_email)
                    .addComponent(jTextField_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_addI)
                    .addComponent(jButton_ADDc))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_addIActionPerformed(java.awt.event.ActionEvent evt) {
        if (!crs.isinstructorsExist(jTextField_email.getText())) {
            String email = String.valueOf(jTextField_email.getText().toString());
            String instructor_name = jTextField_Iname.getText();
            String course_name = jComboBox_cname.getSelectedItem().toString();
            String module_name = String.valueOf(jTextField_mname.getText().toString());
            
            crs.insertUpdateDeleteinstructors('i', null, instructor_name, course_name, module_name,email);

            try {
                AdminInstructor rgf = new AdminInstructor();
                rgf.setVisible(true);
                rgf.pack();
                rgf.setLocationRelativeTo(null);
                rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                this.dispose();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }

        } else {
            JOptionPane.showMessageDialog(null, "instructor Already Exists");
        }
    }

    private void jButton_ADDcActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_ADDcActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jButton_ADDcActionPerformedjLabel6

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addInstructor.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addInstructor.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addInstructor.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addInstructor.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addInstructor().setVisible(true);
            }
        });
    }

    public DefaultComboBoxModel get_courses() {
        Connection con = MyConnection.getConnection();
        PreparedStatement ps;
        // jComboBox_coursename.setModel(new javax.swing.DefaultComboBoxModel<>(new
        // String[] { "BIT", "BBA", "BIBM" }));
        // jComboBox_cname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]
        // { "BIT", "BBA", "BIBM", " bsc CS IT" }));

        DefaultComboBoxModel courses = new javax.swing.DefaultComboBoxModel<>(new String[] {});
        try {
            ps = con.prepareStatement("SELECT name FROM `course`");
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {

                String course_name = rs.getString(1);
                courses.addElement(course_name);
            }
        } catch (SQLException ex) {
            Logger.getLogger(course.class.getName()).log(Level.SEVERE, ex.getMessage(), ex);
        }
        return courses;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_ADDc;
    private javax.swing.JButton jButton_addI;
    private javax.swing.JComboBox<String> jComboBox_cname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField_Iname;
    private javax.swing.JTextField jTextField_email;
    private javax.swing.JTextField jTextField_mname;
    private javax.swing.JLabel jlabel_email;
    // End of variables declaration//GEN-END:variables
}
