/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javastdapp;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JComboBox;
import java.awt.event.*;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.*;
import javax.swing.*;

/**
 *
 * @author shreeya
 */
public class addInstructor extends javax.swing.JFrame {

    /**
     * Creates new form addInstructor
     */
    instructors crs = new instructors();

    public addInstructor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_uname = new javax.swing.JTextField();
        jButton_addI = new javax.swing.JButton();
        jButton_ADDc = new javax.swing.JButton();
        jlabel_email = new javax.swing.JLabel();
        jTextField_first = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField_last = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_phone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_address = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField_email = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jComboBox_gender = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jComboBox_course = new javax.swing.JComboBox<>();
        jPasswordField_pass = new javax.swing.JPasswordField();
        jPasswordField_cpass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel1.setText("Add Instructor");

        jLabel2.setText("Username:");

        jLabel3.setText("Password:");

        jLabel4.setText("Confirm password:");

        jButton_addI.setBackground(new java.awt.Color(0, 51, 51));
        jButton_addI.setForeground(new java.awt.Color(242, 242, 242));
        jButton_addI.setText("Add Instructor");
        jButton_addI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addIActionPerformed(evt);
            }
        });

        jButton_ADDc.setBackground(new java.awt.Color(0, 51, 51));
        jButton_ADDc.setForeground(new java.awt.Color(242, 242, 242));
        jButton_ADDc.setText("Cancel");
        jButton_ADDc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ADDcActionPerformed(evt);
            }
        });

        jlabel_email.setText("First name:");

        jLabel5.setText("Last name:");

        jLabel6.setText("Phone number:");

        jLabel7.setText("Address:");

        jLabel8.setText("Email:");

        jLabel9.setText("Gender:");

        jComboBox_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        jLabel10.setText("Course:");

        jComboBox_course.setModel(this.get_courses());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jlabel_email)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_uname)
                            .addComponent(jTextField_first)
                            .addComponent(jTextField_last)
                            .addComponent(jTextField_phone)
                            .addComponent(jTextField_address)
                            .addComponent(jTextField_email)
                            .addComponent(jComboBox_gender, 0, 137, Short.MAX_VALUE)
                            .addComponent(jComboBox_course, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPasswordField_pass)
                            .addComponent(jPasswordField_cpass))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addComponent(jButton_addI)
                .addGap(83, 83, 83)
                .addComponent(jButton_ADDc)
                .addGap(105, 105, 105))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_uname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jPasswordField_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jPasswordField_cpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel_email)
                    .addComponent(jTextField_first, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_last, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jComboBox_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jComboBox_course, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_addI)
                    .addComponent(jButton_ADDc))
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_addIActionPerformed(java.awt.event.ActionEvent evt) {
        if (!crs.isinstructorsExist(jTextField_last.getText())) {
                String fname = jTextField_first.getText();
                String lname = jTextField_last.getText();
                String uname = jTextField_uname.getText();
                String pass = String.valueOf(jPasswordField_pass.getPassword());
                String re_pass = String.valueOf(jPasswordField_cpass.getPassword());

                if(uname.equals(""))
            {
                JOptionPane.showMessageDialog(null, "Add A Username");
            }
            
            else if(pass.equals(""))
            {
                JOptionPane.showMessageDialog(null, "Add A Password");
            }
            else if(!pass.equals(re_pass))
            {
                JOptionPane.showMessageDialog(null, "Retype password");
            }
           
            String email = jTextField_email.getText();
            Integer phone = Integer.parseInt(jTextField_phone.getText());
            String address = jTextField_address.getText();

            String course = jComboBox_course.getSelectedItem().toString();
            // int hours = Integer.valueOf(jSpinner_courseHours.getValue().toString());
            crs.insertUpdateDeleteinstructors('i', null,fname, lname, uname, pass,email,phone,address,course);
        try{
            AdminInstructor rgf = new AdminInstructor();
            rgf.setVisible(true);
            rgf.pack();
            rgf.setLocationRelativeTo(null);
            rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
    } catch (Exception e) {
        System.out.println(e.getMessage());
    }
}
}
           

    private void jButton_ADDcActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_ADDcActionPerformed
        Admin asc = new Admin();
        asc.setVisible(true);
        asc.pack();
        asc.setLocationRelativeTo(null);
        asc.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }// GEN-LAST:event_jButton_ADDcActionPerformedjLabel6

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addInstructor.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addInstructor.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addInstructor.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addInstructor.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addInstructor().setVisible(true);
            }
        });
    }

    public DefaultComboBoxModel get_courses() {
        Connection con = MyConnection.getConnection();
        PreparedStatement ps;
        // jComboBox_coursename.setModel(new javax.swing.DefaultComboBoxModel<>(new
        // String[] { "BIT", "BBA", "BIBM" }));
        // jComboBox_cname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]
        // { "BIT", "BBA", "BIBM", " bsc CS IT" }));

        DefaultComboBoxModel courses = new javax.swing.DefaultComboBoxModel<>(new String[] {});
        try {
            ps = con.prepareStatement("SELECT name FROM `course`");
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {

                String course_name = rs.getString(1);
                courses.addElement(course_name);
            }
        } catch (SQLException ex) {
            Logger.getLogger(course.class.getName()).log(Level.SEVERE, ex.getMessage(), ex);
        }
        return courses;
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_ADDc;
    private javax.swing.JButton jButton_addI;
    private javax.swing.JComboBox<String> jComboBox_course;
    private javax.swing.JComboBox<String> jComboBox_gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField_cpass;
    private javax.swing.JPasswordField jPasswordField_pass;
    private javax.swing.JTextField jTextField_address;
    private javax.swing.JTextField jTextField_email;
    private javax.swing.JTextField jTextField_first;
    private javax.swing.JTextField jTextField_last;
    private javax.swing.JTextField jTextField_phone;
    private javax.swing.JTextField jTextField_uname;
    private javax.swing.JLabel jlabel_email;
    // End of variables declaration//GEN-END:variables
}
